//
// Created by Stéphane Breuils on 2021/04/23.
//

#ifndef GADIGITALTRANSFORMATIONCERTIFICATION_UTIL_H
#define GADIGITALTRANSFORMATIONCERTIFICATION_UTIL_H



#endif //GADIGITALTRANSFORMATIONCERTIFICATION_UTIL_H
